#!/usr/bin/env python3

import argparse

def main():
    parser = argparse.ArgumentParser(description='Create a code property graph from C/C++ code using a fuzzy parser')
    parser.add_argument('<input-dir>', type=str, help='source directories containing C/C++ code', nargs="+")
    parser.add_argument("--name", action='store_const', const = 'cpgName', help='optional CPG name')
    args = parser.parse_args()
    
    
if __name__ == '__main__':
   main()
